/**
 * rules-uk.js — Sonuswealth UK Financial Rules & Thresholds
 *
 * AUTO-GENERATED by scripts/update-rules-uk.mjs
 * DO NOT edit manually — run: node scripts/update-rules-uk.mjs
 *
 * Last verified: 2026-05-15
 * Tax year:      2026/27
 * Verified by:   Claude (claude-opus-4-7) with live web search
 *
 * STATUS values:
 *   ENACTED   = law, in force
 *   PROPOSED  = in Finance Bill, not yet Royal Assent
 *   DEFERRED  = delayed or withdrawn
 *
 * GOVERNANCE:
 *   Never hardcode a threshold in HTML/JSX. Read from RULES.*
 *   Run this script after every UK Budget or Finance Bill event.
 *   ANTHROPIC_API_KEY must be set in env.
 */

const RULES = {

  /* ── ISA ──────────────────────────────────────────── */
  isa: {
    annual_allowance: 20000,
    status: 'ENACTED',
    notes: 'Unchanged from 2025/26 at £20,000. From 6 April 2027 a £12,000 Cash ISA sub-limit applies to under-65s (overall £20,000 allowance unchanged). Junior ISA remains £9,000.',
    source: 'https://www.gov.uk/individual-savings-accounts/withdrawing-your-money',
    verified: '2026-05-15'
  },

  /* ── PENSION ──────────────────────────────────────── */
  pension: {
    annual_allowance: 60000,
    status: 'ENACTED',
    source: 'https://www.gov.uk/guidance/check-if-youve-gone-above-the-money-purchase-annual-allowance',
    verified: '2026-05-15',

    mpaa: {
      value: 10000,
      status: 'ENACTED',
      notes: 'Triggered by flexi-access drawdown — IRREVERSIBLE. Cap drops from £60,000 to £10,000/yr permanently.',
      source: 'https://adviser.royallondon.com/technical-central/pensions/contributions-and-tax-relief/money-purchase-annual-allowance/',
      verified: '2026-05-15'
    },

    nmpa: {
      current: 55,
      rising_to: 57,
      rising_date: '2028-04-06',
      status: 'ENACTED',
      notes: 'Normal Minimum Pension Age. Protected pension age rules may apply for some schemes.',
      source: 'https://www.gov.uk/hmrc-internal-manuals/pensions-tax-manual/ptm028000',
      verified: '2026-05-15'
    },

    sipp_iht: {
      status: 'ENACTED',
      effective_date: '2027-04-06',
      bill: 'Finance Act 2026 (Finance (No.2) Bill 2024-26)',
      notes: 'Finance Act 2026 received Royal Assent on 18 March 2026. From 6 April 2027, most unused pension funds and pension death benefits will be brought within the value of a deceased person\'s estate for Inheritance Tax purposes. Effective for deaths on or after 6 April 2027.',
      source: 'https://www.gov.uk/government/publications/inheritance-tax-on-pensions-technical-note/technical-note-inheritance-tax-on-pensions',
      verified: '2026-05-15'
    }
  },

  /* ── CGT ──────────────────────────────────────────── */
  cgt: {
    annual_exempt_amount: 3000,
    status: 'ENACTED',
    source: 'https://www.gov.uk/guidance/capital-gains-tax-rates-and-allowances',
    verified: '2026-05-15',

    rates: {
      basic_rate: 18,
      higher_rate: 24,
      status: 'ENACTED',
      source: 'https://www.gov.uk/capital-gains-tax/rates',
      verified: '2026-05-15'
    }
  },

  /* ── INHERITANCE TAX ─────────────────────────────── */
  iht: {
    nil_rate_band: 325000,
    residence_nil_rate_band: 175000,
    combined_nrb: 500000,
    rate: 40,
    freeze_until: '2031-04-05',
    status: 'ENACTED',
    source: 'https://commonslibrary.parliament.uk/research-briefings/sn00573/',
    verified: '2026-05-15',

    annual_gift_exemption: 3000,
    annual_gift_carryforward_years: 1,
    gift_on_marriage_child: 5000,
    regular_gifts_from_income: 'fully exempt (must be from surplus income)',
    seven_year_taper: true,
    source_gifting: 'https://www.gov.uk/inheritance-tax/gifts',
    verified_gifting: '2026-05-15'
  },

  /* ── STATE PENSION ──────────────────────────────── */
  state_pension: {
    weekly: 241.3,
    annual: 12547.6,
    tax_year: '2026/27',
    state_pension_age: 67,
    status: 'ENACTED',
    source: 'https://www.gov.uk/government/news/over-12-million-pensioners-to-receive-575-state-pension-boost',
    verified: '2026-05-15'
  },

  /* ── INCOME TAX ─────────────────────────────────── */
  income_tax: {
    personal_allowance: 12570,
    basic_rate_limit: 37700,
    higher_rate_threshold: 50270,
    additional_rate_threshold: 125140,
    basic_rate: 20,
    higher_rate: 40,
    additional_rate: 45,
    freeze_until: '2031-04-05',
    status: 'ENACTED',
    source: 'https://www.gov.uk/government/publications/maintaining-income-tax-and-equivalent-national-insurance-contributions-thresholds-until-5-april-2031/income-tax-maintaining-the-personal-allowance-and-the-basic-rate-limit-for-income-tax-and-equivalent-national-insurance-contributions-thresholds-unt',
    verified: '2026-05-15'
  },

  /* ── META ─────────────────────────────────────────── */
  _meta: {
    file: 'rules-uk.js',
    generated_by: 'scripts/update-rules-uk.mjs',
    verified_date: '2026-05-15',
    tax_year: '2026/27',
    next_review: 'Run update-rules-uk.mjs after next UK Budget or Finance Bill event',
    update_command: 'node scripts/update-rules-uk.mjs'
  }
};

/* ── Convenience helpers for UI ─────────────────────── */

const RULES_DAYS_TO_SIPP_DEADLINE = (() => {
  const target = new Date(RULES.pension.sipp_iht.effective_date);
  const today = new Date();
  return Math.round((target - today) / (1000 * 60 * 60 * 24));
})();

const RULES_SIPP_STATUS_LABEL = {
  ENACTED:  '6 Apr 2027 · deadline',
  PROPOSED: '6 Apr 2027 · proposed',
  DEFERRED: '6 Apr 2027 · deferred'
}[RULES.pension.sipp_iht.status] || '6 Apr 2027 · check status';

const RULES_SIPP_COPY_SUFFIX = RULES.pension.sipp_iht.status === 'ENACTED'
  ? ''
  : ' (subject to legislation)';
